### PR TITLE
TextEditView: Soft keyboard now opens on first tap and cursor is positioned correctly.

### PR DESCRIPTION
**Pull request by jsdevlover**

### CODE REVIEW

**Comment by collingreen** [comment]
@jsdevlover I'm not seeing either problem on my test phones without your changes (s4, android 4.4.4); iphone 5, ios9.1)

Can you tell me how to reproduce these issues so I can verify your changes fix them?

**Comment by jsdevlover** [comment]
@collingreen , you have already reproduced first part (opening keyboard on first click) and confirmed [here](https://github.com/gameclosure/timestep/issues/69#issuecomment-153181566) (2nd bullet point in Android Summary). 

For cursor position, type in some text in the `TextEditView` lose the focus and try refocusing `TextEditView`. This time the cursor is positioned before the text. It should be positioned at the end of the text.

Please let me know if these are fixed in any of the latest commits and if yes let me know the devkit-core version I should use.
Thanks.

**Comment by collingreen** [comment]
You're right! I apparently have two textedit test apps - one shows these issues, the other does not. Digging into the differences now.

**Comment by collingreen** [comment]
More follow ups in the posted issue. tl;dr - 3 letter color codes seem to be an issue.

**Comment by jsdevlover** [comment]
Since we have identified the correct issue. I'm closing this PR.

**Pull request closed without merging**
